---
project_name: fzf

before:
  hooks:
    - go mod download

builds:
  - id: fzf-macos
    binary: fzf
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - "-s -w -X main.version={{ .Version }} -X main.revision={{ .ShortCommit }}"
  

  - goos:
      - linux
  
    goarch:
      - 386
 
    ldflags:
      - "-s -w -X main.version={{ .Version }} -X main.revision={{ .ShortCommit }}"
 

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - non-existent*

release:
  github:
    owner: tomasky
    name: fzf
  prerelease: auto
  name_template: '{{ .Tag }}'

snapshot:
  name_template: "{{ .Tag }}-devel"

changelog:
  sort: asc
  filters:
    exclude:
      - README
      - test
