---
name: Test fzf on Linux

on:
  push:
    branches: [ master, devel ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.16]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: 'junegunn/fzf'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    
    - name: Unit test
      run: make test
    -
      name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
